#!/usr/bin/env python3
"""Offline, standard-library installer for Codex Model Router (Python 3.11+)."""

import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import sys
import tempfile
import tomllib
import uuid

PACKAGE = Path(__file__).resolve().parent
NAME = "codex-model-router"
TIERS = ("fast", "standard", "deep")
START = "<!-- CODEX_MODEL_ROUTER:START -->"
END = "<!-- CODEX_MODEL_ROUTER:END -->"
EFFORTS = {"none", "minimal", "low", "medium", "high", "xhigh", "max", "ultra"}


def load_mapping(path):
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict) or set(data) != {"version", "tiers"}:
        raise ValueError("Mapping must contain only version and tiers")
    if type(data["version"]) is not int or data["version"] != 1:
        raise ValueError("Unsupported mapping version; expected 1")
    if not isinstance(data["tiers"], dict) or set(data["tiers"]) != set(TIERS):
        raise ValueError("Mapping requires fast, standard, and deep tiers")
    for tier in TIERS:
        entry = data["tiers"][tier]
        if not isinstance(entry, dict) or set(entry) != {"model", "reasoning_effort"}:
            raise ValueError(f"Invalid fields for {tier}")
        if not isinstance(entry["model"], str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}", entry["model"]):
            raise ValueError(f"Invalid model ID for {tier}")
        if not isinstance(entry["reasoning_effort"], str) or entry["reasoning_effort"] not in EFFORTS:
            raise ValueError(f"Invalid reasoning effort for {tier}")
    return data


def render_role(tier, entry):
    purpose = {
        "fast": "Narrow lookup, extraction, and low-risk mechanical edits with clear checks.",
        "standard": "Bounded implementation, reproducible debugging, and focused verification.",
        "deep": "Architectural tradeoffs, difficult diagnosis, and cross-module correctness reasoning.",
    }[tier]
    instructions = (
        "Follow the user's language and the parent task's authorization and project rules. "
        + purpose + " Complete only the assigned slice. You share the workspace: edit only owned files "
        "and preserve others' changes. You are an execution subagent, not a router: do not load "
        "codex-model-router, spawn descendants, or invoke OMX or another orchestrator. "
        "For read-only assignments, do not edit files. Use prior evidence and preserve valid progress. "
        "Report the result, changed files or cited locations, checks actually run and their outcomes, "
        "unresolved assumptions, and complete / needs_escalation / blocked status. "
        "Escalate scope changes or reasoning limitations to the parent. Missing credentials, permissions, "
        "data, or tools are blockers, not reasons to evade restrictions. "
        "Do not claim that a model name in instructions proves the actual executing model."
    )
    fields = {
        "name": f"codex-router-{tier}",
        "description": f"Codex Model Router {tier} tier. {purpose}",
        "model": entry["model"],
        "model_reasoning_effort": entry["reasoning_effort"],
        "developer_instructions": instructions,
    }
    text = "# Generated by codex-model-router; update via install.py --config.\n"
    text += "".join(f"{key} = {json.dumps(value, ensure_ascii=False)}\n" for key, value in fields.items())
    assert tomllib.loads(text) == fields
    return text.encode("utf-8")


def update_entry(original, skill_path):
    # Preserve original bytes, including unrelated newlines and an existing UTF-8 BOM.
    original.decode("utf-8-sig")
    newline = b"\r\n" if b"\r\n" in original else b"\n"
    text = (
        START + "\n## Codex Model Router\n\n"
        "For ordinary engineering tasks with useful independent subtasks, the parent should load "
        f"`{skill_path.as_posix()}` and follow its configurable native model tiers. "
        "This route requires no OMX runtime. Respect explicit workflows, user model choices, "
        "project rules, approval requirements, and live tool constraints. Simple conversation "
        "and work without useful delegation stay with the parent. Delegated agents must not "
        "reroute or spawn descendants. Never claim that the parent model changed.\n" + END
    ).encode("utf-8").replace(b"\n", newline)
    begin, end = START.encode(), END.encode()
    if begin not in original and end not in original:
        separator = b"" if not original else (newline if original.endswith(b"\n") else newline * 2)
        return original + separator + text + newline
    if original.count(begin) != 1 or original.count(end) != 1:
        raise ValueError("Malformed or duplicate CODEX_MODEL_ROUTER markers in AGENTS.md")
    left, right = original.index(begin), original.index(end)
    if right < left:
        raise ValueError("Reversed CODEX_MODEL_ROUTER markers in AGENTS.md")
    return original[:left] + text + original[right + len(end):]


def check_target(root, path):
    path.relative_to(root)
    if not path.resolve().is_relative_to(root):
        raise ValueError(f"Target escapes Codex home: {path}")
    for item in (path, *path.parents):
        if item == root:
            break
        is_junction = getattr(item, "is_junction", lambda: False)
        if item.is_symlink() or is_junction():
            raise ValueError(f"Refusing linked installation target: {item}")
    if path.exists() and not path.is_file():
        raise ValueError(f"Expected a regular file: {path}")


def write_atomic(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".router-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as output:
            output.write(data)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def install(home, config=None, dry_run=False):
    home = Path(home).expanduser().resolve()
    destination = home / "skills" / NAME
    installed_mapping = destination / "models.json"
    check_target(home, installed_mapping)
    source = Path(config).expanduser().resolve() if config else (
        installed_mapping if installed_mapping.exists() else PACKAGE / "skill/models.json"
    )
    mapping = load_mapping(source)
    plan = {
        destination / "SKILL.md": (PACKAGE / "skill/SKILL.md").read_bytes(),
        destination / "agents/openai.yaml": (PACKAGE / "skill/agents/openai.yaml").read_bytes(),
        installed_mapping: (json.dumps(mapping, ensure_ascii=False, indent=2) + "\n").encode("utf-8"),
    }
    for tier in TIERS:
        plan[home / "agents" / f"codex-router-{tier}.toml"] = render_role(tier, mapping["tiers"][tier])
    agents = home / "AGENTS.md"
    check_target(home, agents)
    original = agents.read_bytes() if agents.exists() else b""
    plan[agents] = update_entry(original, destination / "SKILL.md")
    changes = {}
    for path, data in plan.items():
        check_target(home, path)
        before = path.read_bytes() if path.exists() else None
        if before != data:
            changes[path] = (before, data)
    report = {"dry_run": dry_run, "codex_home": str(home), "mapping_source": str(source),
              "changed_files": [str(p.relative_to(home)) for p in changes], "backup": None}
    if (home / "skills/model-router").exists() or b"NATIVE_MODEL_ROUTER:START" in original:
        report["legacy_notice"] = "Legacy model-router remains installed; review duplicate routing entries separately."
    if dry_run or not changes:
        return report
    # Snapshot all replaced files before any installed file is modified.
    existing = {p: old for p, (old, _) in changes.items() if old is not None}
    if existing:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "-" + uuid.uuid4().hex[:8]
        backup = home / "backups" / NAME / stamp
        for path, data in existing.items():
            target = backup / path.relative_to(home)
            check_target(home, target)
            write_atomic(target, data)
        report["backup"] = str(backup)
    written = []
    try:
        for path, (_, data) in changes.items():
            write_atomic(path, data)
            written.append(path)
    except Exception:
        for path in reversed(written):
            before = changes[path][0]
            if before is None:
                path.unlink()
            else:
                write_atomic(path, before)
        raise
    return report


def main():
    # Keep redirected JSON output stable on Windows as well as UTF-8 terminals.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--codex-home", type=Path, default=Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex"))
    parser.add_argument("--config", type=Path, help="Explicit model mapping; otherwise preserve an installed mapping")
    parser.add_argument("--dry-run", action="store_true", help="Validate and preview without writing anything")
    args = parser.parse_args()
    try:
        print(json.dumps(install(args.codex_home, args.config, args.dry_run), ensure_ascii=False, indent=2))
    except (OSError, ValueError) as error:
        parser.exit(1, f"Installation failed: {error}\n")


if __name__ == "__main__":
    main()
